# 捕获错误

1. 捕获错误之显示异常: throw 只能用于同步方法，或者异步方法中异常发生前。

   ```code
   function format_name(name){
    if(!name){
        throw new Error("name is required");
    }
   }
   try{
      format_name();
   }catch(e){
       console.log(e.message,e.stack);
   }
   ```

2. 捕获错误之隐式异常

   - 最常见的是 ReferenceError 错误：变量或属性的引用未找到时会触发这个错误。

   ```code
   function test(err,data){
       console.log(dat)  //这句会发生错误
   }
   test();
   ```

   - 另一个很常见的类似情况是：SyntaxError，比如用 JSON.parse 解析无效的 JSON 数据：

   ```code
   JSON.parse("undefined");
   ```

3. 捕获错误之“错误事件”

   ```code
   var Event_Emitter = require("events").EventEmitter;
    var ee = new Event_Emitter();

    ee.on("error",function(err){    //必须加入错误处理函数；不加的话，没有错误接收函数，会报错
        console.log(err.message);
    });

    ee.emit("error",new Error("no handler to catch me"));
   ```

4. 捕获错误之“错误参数”

   ```code
    var fs = require("fs");
    fs.readFile("./no_file.txt",function(err,buf){
        var data = buf.toString();         	//no_file.txt不存在，这一行会出错
    });
   ```

5. 捕获错误之“未捕获的异常”
   使用域，可以让发代码运行在一个沙盒中、可以更好的监控部分代码。如果我们怀疑哪部分代码有问题，可以使用这种方法，监控、将错误提示给用户端，当然也可以输出日志协助我们找到问题点、解决问题。

   ```code
   var http = require("http");
   var domain = require("domain");

    var d = domain.create();
    d.run(function(){
        var server = http.createServer(function(req,res){
            d.on("error",function(er){
                res.statusCode = 500;
                res.end("internal server error");
                server.close();
                setTimeout(process.exit(),3000,1);
            })
            response.end("Hello JShaman.com");
        });

        server.listen(8000);
    });
   ```
